[package]
name = "fileconverter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

image = "*"
gio = "0.9"
glib = "0.10"
gtk4 = "0.6.6"
